apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eu8a0m9sg-java-quarkus 
  janus-idp.io/tekton: eu8a0m9sg-java-quarkus
  backstage.io/kubernetes-id: eu8a0m9sg-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eu8a0m9sg-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml