apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eu8a0m9sg-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tnevrlka-rhtap/rhtap-qe-java-quarkus:github-6cd8bc644e21a46786e40437522ef0537c031357
          name: container-image
